const DELIVERY_AREA_REQUEST = 'DELIVERY_AREA_REQUEST';
const DELIVERY_AREA_SUCCESS = 'DELIVERY_AREA_SUCCESS';
const DELIVERY_AREA_ERROR = 'DELIVERY_AREA_ERROR';

export { DELIVERY_AREA_REQUEST, DELIVERY_AREA_SUCCESS, DELIVERY_AREA_ERROR };
