const ADD_POINT = 'ADD_POINT';
const REMOVE_POINT = 'REMOVE_POINT';
const REMOVE_ALL_POINTS = 'REMOVE_ALL_POINTS';

const SELECT_VERTEX = 'SELECT_VERTEX';
const UNSELECT_VERTEX = 'UNSELECT_VERTEX';
const UPDATE_VERTEX = 'UPDATE_VERTEX';

export { ADD_POINT, REMOVE_POINT, REMOVE_ALL_POINTS, SELECT_VERTEX, UNSELECT_VERTEX, UPDATE_VERTEX };
