const SET_LOGGEDIN = 'SET_LOGGEDIN';
const LOGGEDIN_REQUEST = 'LOGGEDIN_REQUEST';
const LOGGEDIN_SUCCESS = 'LOGGEDIN_SUCCESS';
const LOGGEDIN_ERROR = 'LOGGEDIN_ERROR';

const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
const USER_DATA_ERROR = 'USER_DATA_ERROR';
const SET_USER_DATA = 'SET_USER_DATA';

export {
  USER_DATA_REQUEST,
  USER_DATA_SUCCESS,
  USER_DATA_ERROR,
  SET_USER_DATA,
  LOGGEDIN_REQUEST,
  LOGGEDIN_SUCCESS,
  LOGGEDIN_ERROR,
  SET_LOGGEDIN,
};
