const DELIVERY_AREAS_REQUEST = 'DELIVERY_AREAS_REQUEST';
const DELIVERY_AREAS_SUCCESS = 'DELIVERY_AREAS_SUCCESS';
const DELIVERY_AREAS_ERROR = 'DELIVERY_AREAS_ERROR';

export { DELIVERY_AREAS_REQUEST, DELIVERY_AREAS_SUCCESS, DELIVERY_AREAS_ERROR };
