const RESTAURANT_DATA_REQUEST = 'RESTAURANT_DATA_REQUEST';
const RESTAURANT_DATA_SUCCESS = 'RESTAURANT_DATA_SUCCESS';
const RESTAURANT_DATA_ERROR = 'RESTAURANT_DATA_ERROR';

export { RESTAURANT_DATA_REQUEST, RESTAURANT_DATA_SUCCESS, RESTAURANT_DATA_ERROR };
