const TOGGLE_DRAW = 'TOGGLE_DRAW';
const TOGGLE_SELECT = 'TOGGLE_SELECT';
const TOGGLE_DELETE = 'TOGGLE_DELETE';
const SET_EDITED = 'SET_EDITED';
const SET_DELETED = 'SET_DELETED';
const RESET_CHANGED = 'RESET_CHANGED';

export { TOGGLE_DRAW, TOGGLE_SELECT, TOGGLE_DELETE, SET_EDITED, SET_DELETED, RESET_CHANGED };
