const SET_LOGGEDIN = 'SET_LOGGEDIN';
const LOGGEDIN_REQUEST = 'LOGGEDIN_REQUEST';
const LOGGEDIN_SUCCESS = 'LOGGEDIN_SUCCESS';
const LOGGEDIN_ERROR = 'LOGGEDIN_ERROR';

export { LOGGEDIN_REQUEST, LOGGEDIN_SUCCESS, LOGGEDIN_ERROR, SET_LOGGEDIN };
