const TOGGLE_DRAWMODE = 'TOGGLE_DRAWMODE';
const CREATE_POLYGON = 'CREATE_POLYGON';
const REMOVE_POLYGON = 'REMOVE_POLYGON';
const SAVE_POLYGON = 'SAVE_POLYGON';
const ACTIVATE_POLYGON = 'ACTIVATE_POLYGON';
const ADD_POINT = 'ADD_POINT';
const REMOVE_POINT = 'REMOVE_POINT';
const REMOVE_ALL_POINTS = 'REMOVE_ALL_POINTS';

const SELECT_VERTEX = 'SELECT_VERTEX';
const UNSELECT_VERTEX = 'UNSELECT_VERTEX';
const UPDATE_VERTEX = 'UPDATE_VERTEX';

export {
  TOGGLE_DRAWMODE,
  ADD_POINT,
  REMOVE_POINT,
  REMOVE_ALL_POINTS,
  SELECT_VERTEX,
  UNSELECT_VERTEX,
  UPDATE_VERTEX,
  CREATE_POLYGON,
  ACTIVATE_POLYGON,
  SAVE_POLYGON,
  REMOVE_POLYGON,
};
