const TOGGLE_DRAWMODE = 'TOGGLE_DRAWMODE';
const TOGGLE_SELECTMODE = 'TOGGLE_SELECTMODE';
const TOGGLE_DELETEMODE = 'TOGGLE_DELETEMODE';

const CREATE_AREA = 'CREATE_AREA';
const DELETE_AREA = 'DELETE_AREA';
const SAVE_AREA = 'SAVE_AREA';
const ACTIVATE_AREA = 'ACTIVATE_AREA';
const DEACTIVATE_AREA = 'DEACTIVATE_AREA';

const ACTIVATE_POLYGON = 'ACTIVATE_POLYGON';
const REMOVE_POLYGON = 'REMOVE_POLYGON';

const ADD_POINT = 'ADD_POINT';
const REMOVE_POINT = 'REMOVE_POINT';
const REMOVE_ALL_POINTS = 'REMOVE_ALL_POINTS';

const SELECT_VERTEX = 'SELECT_VERTEX';
const UNSELECT_VERTEX = 'UNSELECT_VERTEX';
const UPDATE_VERTEX = 'UPDATE_VERTEX';

export {
  TOGGLE_DRAWMODE,
  TOGGLE_SELECTMODE,
  TOGGLE_DELETEMODE,
  CREATE_AREA,
  DELETE_AREA,
  SAVE_AREA,
  ACTIVATE_AREA,
  DEACTIVATE_AREA,
  ACTIVATE_POLYGON,
  REMOVE_POLYGON,
  ADD_POINT,
  REMOVE_POINT,
  REMOVE_ALL_POINTS,
  SELECT_VERTEX,
  UNSELECT_VERTEX,
  UPDATE_VERTEX,
};
