const TOGGLE_DRAWMODE = 'TOGGLE_DRAWMODE';
const TOGGLE_SELECTMODE = 'TOGGLE_SELECTMODE';
const TOGGLE_DELETEMODE = 'TOGGLE_DELETEMODE';

const CREATE_AREA = 'CREATE_AREA';
const DELETE_AREA = 'DELETE_AREA';
const SAVE_AREA = 'SAVE_AREA';
const ACTIVATE_AREA = 'ACTIVATE_AREA';
const DEACTIVATE_AREA = 'DEACTIVATE_AREA';

const ACTIVATE_POLYGON = 'ACTIVATE_POLYGON';

const ADD_POLYGON = 'ADD_POLYGON';
const REMOVE_POLYGON = 'REMOVE_POLYGON';
const ROTATE_POLYGON = 'ROTATE_POLYGON';

const ADD_VERTEX = 'ADD_VERTEX';
const REMOVE_VERTEX = 'REMOVE_VERTEX';

const SELECT_VERTEX = 'SELECT_VERTEX';
const UNSELECT_VERTEX = 'UNSELECT_VERTEX';
const UPDATE_VERTEX = 'UPDATE_VERTEX';

const SET_MINIMUM_ORDER_VALUE = 'SET_MINIMUM_ORDER_VALUE';

export {
  TOGGLE_DRAWMODE,
  TOGGLE_SELECTMODE,
  TOGGLE_DELETEMODE,
  CREATE_AREA,
  DELETE_AREA,
  SAVE_AREA,
  ACTIVATE_AREA,
  DEACTIVATE_AREA,
  ACTIVATE_POLYGON,
  ADD_POLYGON,
  REMOVE_POLYGON,
  ROTATE_POLYGON,
  ADD_VERTEX,
  REMOVE_VERTEX,
  SELECT_VERTEX,
  UNSELECT_VERTEX,
  UPDATE_VERTEX,
  SET_MINIMUM_ORDER_VALUE,
};
